### PR TITLE
New patterns for Dailiza!

### PR DESCRIPTION
**Pull request by Marc-Maxelon**
Dailiza has now three additional patterns:

1. You can share your name with Dailiza and she will respond accordingly.
2. You can ask about the current time and Dailiza will give you the right answer.
3. You can ask who Dailiza is and she will welcome you as well as gladly assist you.

### CODE REVIEW

**Comment by AAPPHH** [comment]
@Marc-Maxelon  We need 3 commits for "Fingerübung 2.1 - Getting started with Git & GitHub" commit 3c695086f85fc936d78f563a10e86d0e6aae9c17 includes 2 patterns and should be split into one commit per pattern.

image

**Comment by AAPPHH** [comment]
@Jonah-gr Hey Jonah, I can't self-assign. Does something need to be enabled?
image

**Comment by Jonah-gr** [comment]
> @Jonah-gr Hey Jonah, I can't self-assign. Does something need to be enabled? image

I have assigned you and hope that it works now.

**Comment by AAPPHH** [comment]
@Jonah-gr Thank you! I can't assign myself. Is there a permission or setting that needs to be enabled?

**Comment by Jonah-gr** [comment]
> @Jonah-gr Thank you! I can't assign myself. Is there a permission or setting that needs to be enabled?

I am not an admin myself and cannot see or change the contributors. If there is a problem with the next portfolio assignment, you can tell me again and I will sort it out with Florian.
The main thing is that you can now rewiew the pr.

**Comment by Marc-Maxelon** [comment]
Thank you for the notation! There are now three commits for each change.

**Comment by AAPPHH** [comment]
Hey Marc,

In commit 0cf7f70c36e2bc240908153e19a30a6444cb04a6, you changed the imports in the file dailizabot/main.py. This is causing a conflict that needs to be resolved before Jonah can merge without issues.

**Pull request merged**
