### PR TITLE
I added The feeling patterns 

### PR DESCRIPTION
**Pull request by Fouad-G**

### CODE REVIEW

**Comment by fouad963** [comment]
Now can the user talk about his feeling

**Comment by fouad963** [comment]
I added the thinking  and the trying pattern

**Comment by Zaydbadla** [comment]
Adding the feeling, thinking, and trying patterns will make the chatbot responses more relatable

**Comment by Zaydbadla** [comment]
@Jonah-gr pull request ready to be merged.

**Pull request merged**
